### PR TITLE
Fixed build for Android, and updated iOS sdk version

### PR DESCRIPTION
**Pull request by thomas-alrek**

### CODE REVIEW

**Comment by linuxs** [comment]
Awesome, I'll check this out and merge it shortly!

**Comment by thomas-alrek** [comment]
Great. By the way, could you enable Issues for your fork? I don't know which of the forks should be considered the new maintainer. But it would be great to have one central place to publish issues

**Comment by okonon** [comment]
Great! Looking forward to it.

**Comment by linuxs** [comment]
It should be merged into the master. Thanks so much for the pull request. Let me know if you see anything else and I'll get it tested asap.

**Comment by okonon** [comment]
@linuxs I also was wondering if you could enable issues on your fork. thanks

**Comment by linuxs** [comment]
@okonon I'll enable it, sorry been extremely busy.

**Pull request merged**
